Models/Emp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace branchingExMVC.Models
{
    public class Emp
    {
        public int Empid { get; set; }
        public string EName { get; set; }
        public string EDesign { get; set; }
        public DateTime? EDoj { get; set; }
    }
}

Controllers/EmpController.cs
using branchingExMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace branchingExMVC.Controllers
{
    public class EmpController : Controller
    {
        // GET: Emp
        public ActionResult Index()
        {
            List<Emp> list = new List<Emp>
            {
                new Emp{Empid=1,EName="sam",EDesign="hr",EDoj=DateTime.Parse("12/12/2021") },
                 new Emp{Empid=2,EName="sree",EDesign="tester",EDoj=DateTime.Parse("1/11/2020") },
                  new Emp{Empid=3,EName="prabhas",EDesign="developer",EDoj=DateTime.Parse("2/12/2021") },
                   new Emp{Empid=4,EName="naveen",EDesign="manager",EDoj=DateTime.Parse("7/4/2020") },
            };
            return View(list);
        }
        
    }
}

Views/Emp/Index.cshtml
@model IEnumerable<branchingExMVC.Models.Emp>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.Partial("PView")
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EDesign)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EDoj)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EDesign)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EDoj)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Empid }) |
                @Html.ActionLink("Details", "Details", new { id = item.Empid }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Empid })
            </td>
        </tr>
    }

</table>

Views/Shared/PView.cshtml
<h1 class="bg-primary text-white text-center">Employee List</h1>
<img src="https://img.freepik.com/free-vector/meeting-business-people-avatar-character_24877-57276.jpg?size=626&ext=jpg" width="200" height="200" />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Emp", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>